### ISSUE TITLE
Not working - syntax error (Yosemite)

### ISSUE THREAD

**Issue by thezeroalpha** [ThomasBrace/Ubersicht-Spotify-widget#1]
It's not working for me, I get "59:64: syntax error: Expected end of line but found identifier (-2741).

Any idea how I could fix this?

**Comment by meridianarc** [comment]
I've noticed the same issue. It seems to have happened right after the new Spotify update.

**Comment by meilon** [comment]
Same problem here and I think that the Spotify update is to blame, too. Happened right after I made the update today.

**Comment by meilon** [comment]
I think this issue can be closed, without a change to the script, it works again after the latest Spotify update.
